
http://localhost:3005/users


### 


http://localhost:3005/users


### 


http://localhost:3005/users/1


### 


http://localhost:3005/users/2


### 


http://localhost:3005/users/2342343


###


http://localhost:3005/users/1;DROP TABLE users;


###

POST http://localhost:3005/users HTTP/1.1
Content-Type: application/json

{
    "username": "anish4",
    "bio": "I am bio 4"
}


### 


PUT http://localhost:3005/users/3 HTTP/1.1
Content-Type: application/json

{
    "username": "anish6",
    "bio": "I am bio 6"
}